---
# tasks file for roles/desktop_env

- name: "Display effective user for desktop_env tasks" # Simplified task name
  ansible.builtin.debug:
    msg: "Running desktop_env tasks as effective user: {{ ansible_effective_user_id }}. (Tasks in this role use 'become')."

- name: Install Hyprland related packages from official repositories
  community.general.pacman:
    name: "{{ hyprland_packages }}"
    state: present
    update_cache: true # Refresh cache before installing this batch of packages

- name: Install SDDM (Display Manager) packages
  community.general.pacman:
    name: "{{ sddm_packages }}"
    state: present
    update_cache: false # Cache updated by previous task

- name: Ensure Hyprland session file exists at /usr/share/wayland-sessions/hyprland.desktop
  ansible.builtin.copy:
    dest: /usr/share/wayland-sessions/hyprland.desktop
    content: |
      [Desktop Entry]
      Name=Hyprland
      Comment=An intelligent dynamic tiling Wayland compositor
      Exec=Hyprland
      Type=Application
      DesktopNames=Hyprland
    mode: '0644'
    owner: root
    group: root

- name: Enable and ensure SDDM service is started
  ansible.builtin.systemd:
    name: sddm.service
    enabled: true # Ensure it starts on boot
    state: started  # Ensure it is running now
