# Hyprpaper configuration for random wallpaper rotation

splash = true
ipc = on

preload = ~/Pictures/WallPappers/

wallpaper {
    monitor =
    path = ~/Pictures/WallPappers/
    timeout = 60
    order = random
    recursive = true
}