# LG ULTRAWIDE - External Display (LEFT SIDE)
monitor=desc:LG Electronics LG ULTRAWIDE 0x0005EAFC, 2560x1080@74.99, auto-left, 1

# LAPTOP SCREEN - BOE eDP-1 (RIGHT SIDE)  
monitor=eDP-1, 2560x1600@240, auto, 1.6

# LG Electronics LG SMART WQHD 0x0101010
monitor=desc:LG Electronics LG SMART WQHD 0x01010101, 3440x1440@99.8,auto-right, 1

#fallback
#monitor=,preferred,auto,auto
