---
- name: Setup Arch Linux Hyprland Workstation
  hosts: archlinux # Corresponds to the group in inventory.ini
  # 'become: true' at the play level means tasks will run as root by default,
  # unless overridden at the task or role level (e.g., for dotfiles).
  become: true
  vars_files:
    - vars/main.yml # Load variables from vars/main.yml
  # Ansible gathers facts about the remote system by default, which is usually desired.
  # gather_facts: true

  pre_tasks:
    - name: Display effective user for pre_tasks (should be root due to become:true)
      ansible.builtin.debug:
        msg: "Running pre_tasks as user: {{ ansible_effective_user_id }} with become: {{ ansible_become }}"
      run_once: true # Run this debug task only once per play

    - name: Update pacman cache (if older than a defined interval or first run)
      community.general.pacman:
        update_cache: true
        upgrade: false # Do not upgrade packages here, dedicated task below
      register: pacman_cache_update # Register output to check if changes were made
      # More reliable change detection for pacman cache update
      changed_when: "'Running transaction' in pacman_cache_update.stdout or 'refreshed' in pacman_cache_update.stdout"
      tags:
        - always # Ensure this runs regardless of other tags

    - name: Display message before full system upgrade
      ansible.builtin.debug:
        msg: "Preparing for full system upgrade (pacman -Syu). This might take some time..."
      tags:
        - base_system
        - packages
      run_once: true

    - name: Perform full system upgrade (equivalent to pacman -Syu)
      community.general.pacman:
        update_cache: false # Cache should be fresh from the previous task
        upgrade: true    # This performs -Syu
      tags:
        - base_system
        - packages

  roles:
    # Apply roles in logical order
    - role: base_system
      tags:
        - base_system # Apply base_system tag to the role itself
        - packages    # Also apply packages tag here
    - role: desktop_env
      tags:
        - desktop_env # Apply desktop_env tag
        - hyprland
        - sddm
    - role: dotfiles
      become: false   # CRITICAL: Dotfiles tasks must run as the target_user, not root
      tags:
        - dotfiles      # Apply dotfiles tag
        - user_config # Apply user_config tag

  post_tasks:
    - name: Playbook finished - Display next steps reminder
      ansible.builtin.debug:
        msg:
          - "Ansible playbook execution complete."
          - "It is HIGHLY RECOMMENDED to REBOOT your system now for all changes to take effect (especially SDDM and user groups)."
          - "After reboot, log in via SDDM and select the Hyprland session."
      run_once: true
      tags:
        - always
