# // █▀█ █▀█ █░█░█ █▀▀ █▀█ █▀ ▄▀█ █░█ █▀▀ █▀█
# // █▀▀ █▄█ ▀▄▀▄▀ ██▄ █▀▄ ▄█ █▀█ ▀▄▀ ██▄ █▀▄


$WORKFLOW_ICON=
$WORKFLOW_DESCRIPTION = Saves as much power as possible by disabling all animations and effects, but preserving readability

decoration {
    shadow {        
        enabled = 0
    }
    blur {
        enabled = 0
        xray = 1
    }
    rounding = 0 
    active_opacity = 1 
    inactive_opacity = 1 
    fullscreen_opacity = 1 
}

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
}

animations:enabled = 0
misc:vfr = true

layerrule {
    match:namespace = ^quickshell:
    no_anim = true
}

layerrule {
    match:namespace = swaync-notification-window
    no_anim = true
}

layerrule {
    match:namespace = swww-daemon
    no_anim = true
}

layerrule {
    match:namespace = rofi
    no_anim = true
}

windowrule = opaque true,match:class (.*) # ensure all windows are opaque 
