include theme.conf

# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# remap to open new kitty tab in the same directory (default is home dir)
map ctrl+shift+t            new_tab_with_cwd

# Uncomment the following 4 lines to minimize kitty latency (higher energy usage)
 input_delay 0
 repaint_delay 2
 sync_to_monitor no
 wayland_enable_ime no 

# change shell to fish
shell /usr/bin/fish

# Enables rich shell features for Fish, Bash, Zsh
shell_integration yes

# ---------------------------------------------------------------------------
# REMOTE CONTROL + CLIPBOARD (for tmux integration and shell features)
# ---------------------------------------------------------------------------
allow_remote_control yes
clipboard_control write-primary write-clipboard

# transparency
background_opacity 0.8

# Appearance
font_family Iosevka Nerd Font
font_features +ss02 +ss04 +ss06 +ss08 +ss10 +ss11 +ss14 +ss16 +ss19 +cv01=1 +cv02=1 +cv08=1 +cv10=1 +cv12=1 +cv16=3 +cv20=1 +cv24=1 +cv25=1 +cv30=1 +cv32=6 +cv36=1 +zero +dlig
bold_font auto
italic_font auto
bold_italic_font auto
enable_audio_bell no
font_size 9.0
window_padding_width 25
cursor_trail 1
